name: panhandler

views:
  - name: ''
    class: CNCView
    menu: Panhandler
    menu_option: Welcome
    attributes:
      template_name: pan_cnc/welcome.html
    context:
      title: Panhandler
      description: Panhandler is a tool to allow sharing of git repositories, which can contain virtually anything.
      documentation_link: https://github.com/PaloAltoNetworks/panhandler/blob/master/docs/snippet_configuration.rst

  - name: import
    class: ImportRepoView
    menu: Panhandler
    menu_option: Import Snippets
    attributes:
      snippet: import_repo
      header: Import Repository
      title: Enter a valid git url and desired branch below
      next_url: view_snippets

  - name: 'view_snippets'
    class: ViewSnippetsView



