name: panhandler
label: Panhandler

repositories:
  - name: Iron-Skillet
    url: https://github.com/PaloAltoNetworks/iron-skillet.git
    branch: panos_v10.1
    destination_directory: Iron-Skillet

application_data:
  recommended_repos_link: http://bit.ly/2XmZ7Il

views:
  - name: ''
    class: WelcomeView
    menu: Panhandler
    menu_option: Welcome
    attributes:
      template_name: panhandler/welcome.html
    context:
      title: Panhandler
      description: description is inline
      documentation_link: https://panhandler.readthedocs.io/en/latest/
      next: collections

  - name: import
    class: ImportRepoView
    menu: Panhandler
    menu_option: Import Skillets
    attributes:
      snippet: import_repo
      header: Import Repository
      title: Enter a valid git URL below
      next_url: view_snippets
      help_text: >
        This view imports a new git repository. Once imported, any skillets defined in that repository will be
        available in the Skillet Collections. Click below for more detailed documentation.
      help_link_title: Import Skillets Documentation
      help_link: https://panhandler.readthedocs.io/en/master/importing_skillets.html

  - name: edit_skillet
    class: UpdateSkilletView
    parameters:
      - repo_name
      - skillet

  - name: edit_skillet_yaml
    class: UpdateSkilletYamlView
    parameters:
      - repo_name
      - skillet

  - name: create_skillet
    class: CreateSkilletView

  - name: collections
    class: ListSkilletCollectionsView
    menu: Panhandler
    menu_option: Skillet Collections

  - name: repos
    class: ListReposView
    menu: Panhandler
    menu_option: Skillet Repositories

  - name: repo_detail
    class: RepoDetailsView
    parameter: repo_name
    attributes:
      help_text: >
        Repository Details allows you to update to the latest version from the upstream git repository. You may
        also use the 'Remove Repository' to remove this repository and all embedded skillets from all Skillet
        Collections

  - name: update_repo
    class: UpdateRepoView
    parameters:
      - repo_name
      - branch

  - name: update_all_repos
    class: UpdateAllReposView

  - name: remove_repo
    class: RemoveRepoView
    parameter: repo_name

  - name: collection
    class: ListSkilletsInCollectionView
    parameter: collection

  - name: skillet
    class: ViewSkilletView
    parameter: skillet

  - name: check_update
    class: CheckAppUpdateView

  - name: validate
    class: ExecuteValidationSkilletView
    parameter: skillet

  - name: validate-results
    class: ViewValidationResultsView

  - name: report
    class: ReportView

  - name: export_valiation_results
    class: ExportValidationResultsView
    parameter: skillet

  - name: favorites
    class: FavoritesView
    menu: Panhandler
    menu_option: Favorites

  - name: add_favorite
    class: AddFavoritesView

  - name: delete_favorite
    class: DeleteFavoriteView
    parameter: favorite

  - name: favorite
    class: FavoriteCollectionView
    parameter: favorite

  - name: favorite_skillet
    class: AddSkilletToFavoritesView
    parameter: skillet_name

  - name: extract_variables
    class: ExtractTemplateVariablesView

  - name: test_skillet
    class: SkilletTestView

  - name: generate_key
    class: GenerateKeyView

  - name: push
    class: PushGitRepositoryView

  - name: copy_skillet
    class: CopySkilletView
    parameters:
      - repo_name
      - skillet_name

  - name: delete_skillet
    class: DeleteSkilletView
    parameters:
      - repo_name
      - skillet_name

  - name: generate_skillet
    class: GenerateSkilletChooserView
    parameter: repo_name

  - name: generate_skillet_connect
    class: GenerateSkilletConnectView

  - name: generate_skillet_online
    class: GenerateSkilletOnlineView

  - name: generate_skillet_offline
    class: GenerateSkilletOfflineView

  - name: generate_skillet_write
    class: CreateSkilletView
    attributes:
      snippet: generate_skillet_write

  - name: generate_skillet_blank
    class: GenerateSkilletBlankView
    attributes:
      header: Skillet Generator
      title: Create a new blank Skillet

  - name: generate_skillet_copy
    class: CreateSkilletView
    attributes:
      header: Skillet Generator
      title: Create a Skillet using a Previously Copied Skillet

  - name: generate_set_skillet_connect
    class: GenerateSetSkilletConnectView

  - name: generate_set_skillet_online
    class: GenerateSetSkilletOnlineView

  - name: generate_set_skillet_offline
    class: GenerateSetSkilletOfflineView

  - name: generate_config_template_connect
    class: GenerateConfigTemplateConnectView

  - name: generate_config_template
    class: GenerateConfigTemplateView

  - name: generate_config_diff_cli
    class: ConfigDiffSetCliConnectView
    menu: PAN-OS Tools
    menu_option: Configuration Diff (Set CLI)
    attributes:
      header: Configuration Diff (Set CLI)

  - name: show_config_diff_cli
    class: ConfigDiffSetCLIOutput

  - name: generate_config_diff_skillet
    class: ConfigDiffSkilletConnectView
    menu: PAN-OS Tools
    menu_option: Configuration Diff (Skillet)
    attributes:
      header: Configuration Diff (Skillet)

  - name: show_config_diff_skillet
    class: ConfigDiffSkilletOutput

  - name: generate_config_diff_ansible
    class: ConfigDiffAnsibleConnectView
    menu: PAN-OS Tools
    menu_option: Configuration Diff (Ansible)
    attributes:
      header: Configuration Diff (Ansible)

  - name: show_config_diff_ansible
    class: ConfigDiffAnsibleOutput