name: panhandler
label: Panhandler

repositories:
  - name: Iron-Skillet
    url: https://github.com/PaloAltoNetworks/iron-skillet.git
    branch: panos_v9.0
    destination_directory: Iron-Skillet

application_data:
  recommended_repos_link: http://bit.ly/2XmZ7Il

views:
  - name: ''
    class: WelcomeView
    menu: Panhandler
    menu_option: Welcome
    attributes:
      template_name: panhandler/welcome.html
    context:
      title: Panhandler
      description: description is inline
      documentation_link: https://panhandler.readthedocs.io/en/latest/
      next: collections

  - name: import
    class: ImportRepoView
    menu: Panhandler
    menu_option: Import Skillets
    attributes:
      snippet: import_repo
      header: Import Repository
      title: Enter a valid git URL below
      next_url: view_snippets
      help_text: >
        This view imports a new git repository. Once imported, any skillets defined in that repository will be
        available in the Skillet Collections. Click below for more detailed documentation.
      help_link_title: Import Skillets Documentation
      help_link: https://panhandler.readthedocs.io/en/master/importing_skillets.html

  #  - name: snippet_types
  #    class: ListSnippetTypesView
  #    menu: Panhandler
  #    menu_option: Template Library

  - name: edit_skillet
    class: UpdateSkilletView
    parameters:
      - repo_name
      - skillet

  - name: collections
    class: ListSkilletCollectionsView
    menu: Panhandler
    menu_option: Skillet Collections

  - name: snippets_by_type
    class: ListSnippetsByGroup
    parameter: service_type

  - name: repos
    class: ListReposView
    menu: Panhandler
    menu_option: Skillet Repositories

  - name: repo_detail
    class: RepoDetailsView
    parameter: repo_name
    attributes:
      help_text: >
        Repository Details allows you to update to the latest version from the upstream git repository. You may
        also use the 'Remove Repository' to remove this repository and all embedded skillets from all Skillet
        Collections

  - name: update_repo
    class: UpdateRepoView
    parameters:
      - repo_name
      - branch

  - name: update_all_repos
    class: UpdateAllReposView

  - name: remove_repo
    class: RemoveRepoView
    parameter: repo_name

  - name: collection
    class: ListSkilletsInCollectionView
    parameter: collection

  - name: skillet
    class: ViewSkilletView
    parameter: skillet

  #  - name: provision
  #    class: ProvisionSnippetView

  - name: check_update
    class: CheckAppUpdateView

  # Test validation views below
  - name: validate
    class: ExecuteValidationSkilletView
    parameter: skillet

  - name: validate-results
    class: ViewValidationResultsView
