version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'export TAG=1.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              echo 'export TAG=dev' >> $BASH_ENV
            else
              echo "Not building other branch"
            fi
            docker build -t paloaltonetworks/panhandler:$TAG .
            echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
            docker push paloaltonetworks/panhandler:$TAG
