name: import_repo
label: Import Git Repository
description: Imports a git repository
type: app
extends:

labels:

variables:
  - name: repo_name
    description: Repository Name
    default: Example_Skillets
    type_hint: text
    allow_special_characters: false
    help_text: The arbitrary name of this Repository.
  - name: url
    description: Git Repository HTTPS URL
    default: https://github.com/PaloAltoNetworks/Skillets.git
    type_hint: text
    help_text: The 'git' link to the repository you would like to import.

snippets:

