name: add_skillet_to_favorite
label: Add Skillet to a Favorite Collection
description: Adds the selected skillet to your Favorite Collections
type: app

variables:
  - name: skillet_name
    description: Skillet Name
    default:
    type_hint: hidden
  - name: favorites
    description: Favorites
    default:
    type_hint: checkbox
    source: all_favorites
